import { isArabic } from './i18n.js'

/**
 * Page text, keyed by the Arabic original.
 *
 * The pages were written in Arabic first, so keying on the Arabic keeps the
 * source readable — a template still says what it says — while giving the
 * English UI a real translation. Anything missing here falls back to the Arabic,
 * which is legible rather than blank, and is fixed by adding one line.
 */
const en = {
  // ---- common labels ----
  'السنة الدراسية': 'Academic year',
  'حذف': 'Delete',
  'الحالة': 'Status',
  'الفصل': 'Class',
  'إغلاق': 'Close',
  'المبلغ': 'Amount',
  'المتبقي': 'Outstanding',
  'الاسم': 'Name',
  'تعديل': 'Edit',
  'الفترة': 'Period',
  'الفئة': 'Category',
  'البريد الإلكتروني': 'Email',
  'نشط': 'Active',
  'إلغاء': 'Cancel',
  'الطالب': 'Student',
  'اسم المستخدم': 'Username',
  'المواد': 'Subjects',
  'رقم الطالب': 'Student no.',
  'اختر السنة الدراسية': 'Choose an academic year',
  'جاري الحفظ...': 'Saving...',
  'الرسم': 'Fee',
  'المدفوع': 'Paid',
  'مفعّل': 'Active',
  'حفظ التعديل': 'Save changes',
  'رمز الفصل': 'Class code',
  'بدون اسم': 'Unnamed',
  'بواسطة': 'by',
  'جاري التحميل...': 'Loading...',
  'التاريخ': 'Date',
  'الاستحقاق': 'Due',
  'الطريقة': 'Method',
  'مادة': 'subject',
  'غير نشط': 'Inactive',
  'عدد الطلبة': 'Students',
  'غير مفعّل': 'Inactive',
  'النوع': 'Type',
  'حفظ': 'Save',
  'الإجمالي': 'Total',
  'الاسم الكامل': 'Full name',
  'المؤهل الأكاديمي': 'Qualification',
  'اسم الفصل': 'Class name',
  'الفصل الدراسي': 'Term',
  'تاريخ النشر': 'Published on',
  'اختر الفصل': 'Choose a class',
  'المادة': 'Subject',
  'الخصم': 'Discount',
  'اسم الفئة': 'Category name',
  'مفعّلة': 'Active',
  'الصافي': 'Net',
  'بتاريخ': 'on',
  'اسم المخطط': 'Scheme name',
  'فعّل': 'Activate',
  'كلمة المرور': 'Password',
  'لا توجد': 'None',
  'إضافة مادة': 'Add subject',
  'إخفاء': 'Hide',
  'بياناته': 'details',
  'تغيير كلمة المرور': 'Change password',
  'لا توجد نتائج مطابقة.': 'No matching results.',
  'الأبناء': 'Children',
  'الصف': 'Grade',
  'طالب': 'student',
  'استرجاع': 'Restore',
  'المواد المسندة': 'Assigned subjects',
  'رقم الهاتف': 'Phone number',
  'رقم هاتف 2': 'Phone number 2',
  'مكان السكن': 'Address',
  'عدد المواد': 'Subjects',
  'مواد': 'subjects',
  'كود المادة': 'Subject code',
  'اسم المادة': 'Subject name',
  'حصص/أسبوع': 'periods/week',
  'الفصول': 'Classes',
  'إضافة فصل': 'Add class',
  'الاستيعاب': 'Capacity',
  'السنة الدراسية الحالية': 'Current academic year',
  'كشوف الدرجات المتاحة': 'Available report cards',
  'تحميل PDF': 'Download PDF',
  'نوع التقرير': 'Report type',
  'السيمستر': 'Semester',
  'السبب': 'Reason',
  'تحديد الكل': 'Select all',
  'طريقة الدفع': 'Payment method',
  'تاريخ الدفع': 'Payment date',
  'رقم المرجع (اختياري)': 'Reference (optional)',
  'جاري التسجيل...': 'Recording...',
  'تسجيل الدفعة وإصدار الإيصال': 'Record payment and issue receipt',
  'كل الفصول': 'All classes',
  'إلى': 'To',
  'عدد الإيصالات': 'Receipts',
  'المستلم': 'Received by',
  'ملغى': 'Voided',
  'سليم': 'Valid',
  'معطّلة': 'Disabled',
  'إلغاء الكل': 'Clear all',
  'إضافة': 'Add',
  'النسبة %': 'Percent %',
  'الإيصالات': 'Receipts',
  'رقم الإيصال': 'Receipt no.',
  'اسم الطالب': 'Student name',
  'نسبة الإنجاز': 'Completion',
  'الأستاذ': 'Teacher',
  'مخططات نظام الدرجات': 'Grading schemes',
  'من الصف': 'From grade',
  'إلى الصف': 'To grade',
  'مجموع الأوزان': 'Total weight',
  'الوزن %': 'Weight %',
  'الفصل الحالي': 'Current class',
  'الطلبة': 'Students',
  'عرض الطلبة': 'View students',
  'أولياء الأمور': 'Guardians',
  'عدد أولياء الأمور': 'Guardians',
  'عرض أولياء الأمور': 'View guardians',
  'الموبايل': 'Mobile',
  'الحساب': 'Account',
  'أدمن': 'Admin',
  'موظف': 'Staff',
  'تعديل الدخول': 'Edit sign-in',
  'تعديل الصلاحيات': 'Edit permissions',
  'كلمة المرور الجديدة': 'New password',
  'صلاحيات': 'Permissions',
  'حفظ الصلاحيات': 'Save permissions',
  'رفع Excel': 'Upload Excel',
  'تأكيد الاستيراد': 'Confirm import',
  'معاينة الاستيراد': 'Preview import',
  'الجدد': 'New',
  'المكررون': 'Duplicates',
  'الأخطاء': 'Errors',
  'الرقم': 'No.',
  'الرقم الوطني': 'National ID',
  'ولي الأمر': 'Guardian',
  'معلومات الطالب المطلوبة': 'Required student details',
  'اختر الجنس': 'Choose gender',
  'ذكر': 'Male',
  'أنثى': 'Female',
  'اختر الصف الدراسي': 'Choose a grade',
  'اختر السنة الدراسية أولاً': 'Choose an academic year first',
  'البحث عن شقيق': 'Sibling search',
  'بيانات ولي الأمر الشخصية': 'Guardian details',
  'رقم ولي الأمر': 'Guardian no.',
  'الاسم الأول': 'First name',
  'اسم العائلة': 'Last name',
  'صلة القرابة': 'Relation',
  'اختر صلة القرابة': 'Choose a relation',
  'الأب': 'Father',
  'الأم': 'Mother',
  'أخرى': 'Other',
  'الهاتف النقال': 'Mobile',
  'بيانات إضافية للطالب': 'Additional student details',
  'حفظ الطالب': 'Save student',
  'اسم المستخدم:': 'Username:',
  'لم يتم إدخال الرقم': 'No number entered',
  'كلمة المرور:': 'Password:',
  'الفصل / الشعبة': 'Class / section',
  'السابق': 'Previous',
  'صفحة': 'Page',
  'إجمالي': 'total',
  'التالي': 'Next',
  'بيانات الطالب': 'Student details',
  'الاسم الكامل:': 'Full name:',
  'الاسم العربي:': 'Arabic name:',
  'البريد:': 'Email:',
  'السنة الدراسية:': 'Academic year:',
  'الفصل:': 'Class:',
  'الجنسية:': 'Nationality:',
  'الرقم الوطني:': 'National ID:',
  'الموبايل:': 'Mobile:',
  'ولي الأمر:': 'Guardian:',
  'اسم مستخدم ولي الأمر:': 'Guardian username:',
  'كلمة مرور ولي الأمر:': 'Guardian password:',
  'الحالة:': 'Status:',
  'مؤرشف': 'Archived',
  'أرشفة': 'Archive',
  'حذف نهائي': 'Delete permanently',
  'إضافة أستاذ': 'Add teacher',
  'الهاتف': 'Phone',
  'تعديل بيانات الأستاذ': 'Edit teacher',
  'كلمة مرور جديدة (اختياري)': 'New password (optional)',
  'البيانات الشخصية': 'Personal details',
  'بيانات الدخول': 'Sign-in details',
  'تأكيد كلمة المرور': 'Confirm password',
  'حفظ الأستاذ': 'Save teacher',
  'رؤية المواد': 'View subjects',
  'إضافة مواد للفصل': 'Add subjects to the class',
  'اختر الفصل الدراسي': 'Choose a class',
  'قبل إضافة مادة.': 'before adding a subject.',
  'عدد الحصص في الأسبوع': 'Periods per week',
  'إضافة مادة أخرى': 'Add another subject',
  'حذف هذا الصف': 'Remove this row',
  'حفظ جميع المواد': 'Save all subjects',
  'الإجراءات': 'Actions',
  'حفظ الفصل': 'Save class',
  'مفعلة': 'Active',
  'إضافة سنة دراسية': 'Add academic year',
  'السنة المفعّلة الآن': 'The active year is now',
  'وهي سنة سابقة.': 'which is a past year.',
  'للعودة إلى السنة الحالية.': 'to return to the current year.',
  'مفعّلة حالياً': 'Currently active',
  'غير مفعّلة': 'Inactive',
  'تفعيل هذه السنة': 'Activate this year',
  'الكلمة الافتتاحية في تقرير السيمستر': 'Semester report opening message',
  'نص الكلمة': 'Message text',
  'حفظ الكلمة': 'Save message',
  'استعادة النص الافتراضي': 'Restore the default text',
  'عرض الدرجات': 'View marks',
  'تقرير Quarter': 'Quarter report',
  'تقرير سيمستر': 'Semester report',
  'الفترة (Quarter)': 'Quarter',
  'السيمستر الأول (Quarter 1 + Quarter 2)': 'Semester 1 (Quarter 1 + Quarter 2)',
  'السيمستر الثاني (Quarter 3 + Quarter 4)': 'Semester 2 (Quarter 3 + Quarter 4)',
  'كل طلاب الفصل (ملف واحد)': 'Whole class (one file)',
  'جاري إنشاء التقرير...': 'Generating the report...',
  'إنشاء التقرير (PDF)': 'Generate report (PDF)',
  'نشر التقرير للطلبة وأولياء الأمور': 'Publish to students and guardians',
  'جاري النشر...': 'Publishing...',
  'إلغاء النشر': 'Unpublish',
  'الفترة المنشورة': 'Published period',
  'الدرجات الناقصة': 'Missing marks',
  'حفظ المواد': 'Save subjects',
  'اعتماد الخصومات': 'Discount approvals',
  'قيمة الرسم': 'Fee amount',
  'مقدّم الطلب': 'Requested by',
  'اعتماد': 'Approve',
  'رفض': 'Reject',
  'دفع رسوم التسجيل': 'Enrolment payment',
  'تم حفظ بيانات': 'Saved',
  'جاري تجهيز رسوم الطالب...': 'Preparing the student’s fees...',
  'لا توجد رسوم مستحقة على هذا الطالب.': 'This student owes nothing.',
  'إجمالي المستحق': 'Total outstanding',
  'المحدد للدفع الآن': 'Being paid now',
  'المدفوع الآن': 'Paid now',
  'متابعة': 'Continue',
  'تخطي — لم يدفع شيئاً': 'Skip — nothing paid',

  // ---- finance reports ----
  'التقارير المالية': 'Financial reports',
  'التقرير': 'Report',
  'الأرصدة غير المسددة': 'Outstanding balances',
  'تقرير المتأخرات': 'Aged debt',
  'المقبوضات خلال فترة': 'Collections over a period',
  'التجميع': 'Group by',
  'هذا الشهر': 'This month',
  'هذه السنة': 'This year',
  'جاري إعداد التقرير...': 'Preparing the report...',
  'إجمالي غير المسدد': 'Total outstanding',
  'لا توجد أرصدة غير مسددة.': 'No outstanding balances.',
  'المتأخر': 'Overdue',
  'أقصى تأخير (يوم)': 'Days late',
  'لا توجد متأخرات.': 'Nothing overdue.',
  'إجمالي المقبوضات': 'Total collected',
  'إيصالات ملغاة': 'Voided receipts',
  'المقبوضات': 'Collections',
  'المحصّل': 'Collected',
  'حسب الموظف المستلم': 'By cashier',
  'حسب طريقة الدفع': 'By payment method',
  'الإيصال': 'Receipt',
  'لا توجد مقبوضات في هذه الفترة.': 'No collections in this period.',

  // ---- fee setup ----
  'الفئات وطرق الدفع': 'Categories and payment methods',
  'فئات الرسوم': 'Fee categories',
  'زي مدرسي': 'Uniform',
  'إضافة فئة': 'Add category',
  'لم تُضف أي فئة بعد.': 'No categories yet.',
  'طرق الدفع': 'Payment methods',
  'اسم الطريقة': 'Method name',
  'شيك': 'Cheque',
  'إضافة طريقة': 'Add method',
  'تعديل قالب رسم': 'Edit fee template',
  'إضافة قالب رسم': 'Add fee template',
  'اسم الرسم': 'Fee name',
  'اختر الفئة': 'Choose a category',
  'تاريخ الاستحقاق': 'Due date',
  'إلزامي (يُسند تلقائياً)': 'Mandatory (raised automatically)',
  'لا توجد فصول لهذه السنة الدراسية.': 'No classes for this academic year.',
  'السنة': 'Year',
  'الصفوف': 'Grades',
  'كل الصفوف': 'All grades',
  'لا توجد قوالب بعد.': 'No templates yet.',
  'تعديل قاعدة خصم': 'Edit discount rule',
  'إضافة قاعدة خصم': 'Add discount rule',
  'اسم القاعدة': 'Rule name',
  'خصم الإخوة (تلقائي)': 'Sibling discount (automatic)',
  'نسبة ثابتة': 'Fixed percentage',
  'مبلغ ثابت': 'Fixed amount',
  'ترتيب الابن': 'Child ordinal',
  'نسبة الخصم %': 'Discount %',
  'إضافة شريحة': 'Add tier',
  'القاعدة': 'Rule',
  'تُطبَّق على': 'Applies to',
  'القيمة': 'Value',
  'إخوة': 'Siblings',
  'نسبة': 'Percentage',
  'مبلغ': 'Amount',
  'كل الفئات': 'All categories',
  'الابن': 'Child',
  'لا توجد قواعد خصم بعد.': 'No discount rules yet.',

  // ---- student accounts ----
  'حسابات الطلبة': 'Student accounts',
  'بحث عن طالب': 'Find a student',
  'ابحث عن طالب لعرض حسابه المالي.': 'Search for a student to see their account.',
  'جاري تحميل كشف الحساب...': 'Loading the statement...',
  'إسناد رسوم السنة': 'Raise this year’s fees',
  'الخصومات': 'Discounts',
  'متأخرات مستحقة:': 'Overdue:',
  'الرسوم والخصومات': 'Fees and discounts',
  'طلب خصم': 'Request discount',
  'معتمد': 'Approved',
  'بانتظار الاعتماد': 'Awaiting approval',
  'مرفوض': 'Rejected',
  'اعتمده': 'Approved by',
  'لم تُسند رسوم لهذا الطالب بعد.': 'No fees raised for this student yet.',
  'تحصيل دفعة': 'Take a payment',
  'تخصيص آلي (الأقدم استحقاقاً أولاً)': 'Automatic allocation (earliest due first)',
  'تخصيص يدوي': 'Manual allocation',
  'المبلغ المخصص': 'Allocated',
  'بلا تاريخ': 'No date',
  'مجموع التخصيص:': 'Allocated total:',
  'المبلغ:': 'Amount:',
  'لا توجد إيصالات.': 'No receipts.',
  'أو مبلغ ثابت': 'or a fixed amount',
  'إرسال الطلب': 'Send request',

  // ---- grade management ----
  'جاري تحميل الفصول...': 'Loading classes...',
  'لا توجد مواد لهذا الفصل.': 'This class has no subjects.',
  'بدون اسم فصل': 'Unnamed class',
  'العودة للفصول': 'Back to classes',
  'المادة:': 'Subject:',
  'الأستاذ:': 'Teacher:',
  'الفئة الدراسية:': 'Grading scheme:',
  'غير محددة': 'Not set',
  'الساعات المعتمدة:': 'Credits earned:',
  'حصص/أسبوع)': 'periods/week)',
  'الفصل الدراسي:': 'Term:',
  'جاري إعادة الفتح...': 'Reopening...',
  'إعادة فتح للأستاذ': 'Reopen for the teacher',
  'جاري تحميل كشف الدرجات...': 'Loading the mark sheet...',
  'تم إرسال الدرجات': 'Marks submitted',
  'أُرسلت': 'Submitted',
  'لا يوجد طلاب نشطون مسجلون في هذا الفصل.': 'No active students are enrolled in this class.',
  'المجموع / 100': 'Total / 100',
  'جاري الإرسال...': 'Submitting...',
  'إرسال نهائي': 'Submit finally',
  'صحح الدرجات غير الصحيحة قبل الحفظ.': 'Correct the invalid marks before saving.',
  'حسب الكوارتر': 'By quarter',
  'حسب السيمستر': 'By semester',
  'السيمستر الأول (كوارتر 1 + 2)': 'Semester 1 (Quarters 1 + 2)',
  'السيمستر الثاني (كوارتر 3 + 4)': 'Semester 2 (Quarters 3 + 4)',
  'عرض التقرير': 'Show report',
  'طباعة PDF': 'Print PDF',
  'إجمالي المواد': 'Subjects',
  'تم الإرسال': 'Submitted',
  'بدأ ولم يرسل': 'Started, not submitted',
  'لم يبدأ': 'Not started',
  'المواد المتبقية': 'Remaining subjects',
  'إخفاء التفاصيل': 'Hide details',
  'عرض التفاصيل': 'Show details',
  'المواد المرسلة': 'Submitted subjects',

  // ---- grading settings ----
  'إعداد نظام النقاط': 'Grade point setup',
  'مخطط جديد': 'New scheme',
  'مثال: G1-4': 'e.g. G1-4',
  'حفظ المخطط': 'Save scheme',
  'الفئات': 'Categories',
  'لم تُحدَّد فصول': 'No classes chosen',
  'تعديل التقسيم': 'Edit the split',
  'تفعيل المخطط': 'Activate scheme',
  'إلغاء التفعيل': 'Deactivate',
  'مخططات جاهزة — القسم الأمريكي': 'Ready-made schemes — American Department',
  'إنشاء هذا المخطط': 'Create this scheme',
  'تقسيم الدرجات': 'Mark split',
  'العودة للمخططات': 'Back to schemes',
  'حفظ التغييرات': 'Save changes',
  'لديك تعديلات غير محفوظة.': 'You have unsaved changes.',
  'كل التغييرات محفوظة.': 'All changes saved.',
  'هذا المخطط': 'This scheme is',
  'متبقٍ': 'remaining',
  'لتكتمل المئة.': 'to reach 100%.',
  'تجاوزت المئة بـ': 'over 100% by',
  'المخطط مكتمل.': 'the scheme is complete.',
  'حذف الفئة': 'Delete category',
  'مجموع درجات بنود هذه الفئة:': 'Total marks across this category’s items:',
  'البند': 'Item',
  'الدرجة القصوى': 'Max score',
  'معطّل': 'Disabled',
  'اسم بند جديد': 'New item name',
  'إضافة بند': 'Add item',
  'الفصول التي تعمل بهذا المخطط': 'Classes using this scheme',
  'حفظ الفصول': 'Save classes',
  'إضافة فئة جديدة': 'Add a category',
  'مثال: Quizzes': 'e.g. Quizzes',
  'إضافة الفئة': 'Add category',
  'درجات ستُحذف': 'Marks to be deleted',
  'طلبة متأثرون': 'Students affected',
  'الفصول المتأثرة:': 'Classes affected:',
  'أفهم أن': 'I understand that',
  'إلغاء التفعيل وحذف الدرجات': 'Deactivate and delete the marks',
  'تراجع': 'Go back',
  'جدول النقاط المكتسبة': 'Legend of credits earned',
  'إضافة صف': 'Add row',
  'عدد الحصص في الأسبوع (40 دقيقة)': 'Periods per week (40 min)',
  'سلم تقدير الدرجات': 'Grading / GPA scale',
  'إضافة تقدير': 'Add band',
  'التقدير': 'Letter',
  'أصغر درجة': 'Min score',
  'أعلى درجة': 'Max score',
  'النقاط (GPA)': 'Points (GPA)',
  'حفظ إعدادات نظام النقاط': 'Save grade point settings',
  'الساعات المعتمدة لهذه المادة:': 'Credits earned for this subject:',

  // ---- term windows ----
  'فتح وإغلاق الفصول الدراسية': 'Open and close terms',
  'مفتوح': 'Open',
  'مغلق': 'Closed',
  'فُتح': 'Opened',
  'أُغلق': 'Closed',
  'لم يُفتح بعد.': 'Not opened yet.',
  'إغلاق الفصل': 'Close the term',
  'فتح الفصل': 'Open the term',

  // ---- parent / student portal ----
  'جاري تحميل الدرجات...': 'Loading marks...',
  'درجات': 'Marks for',
  'الحساب المالي': 'Account',
  'يوجد مبلغ متأخر قدره': 'There is an overdue amount of',
  'يرجى مراجعة إدارة المدرسة.': 'Please contact the school office.',
  'إجمالي الرسوم': 'Total fees',
  'تفاصيل الرسوم': 'Fee details',
  'لا توجد مواد لعرضها في هذه الفترة.': 'No subjects to show for this period.',
  'الوزن': 'Weight',
  'النسبة': 'Percent',
  'النقاط': 'Points',
  'لم تُرصد': 'Not marked',
  'بانتظار رصد:': 'Awaiting marks:',

  // ---- promotion ----
  'نقل الطلبة إلى الصف التالي': 'Move students up a grade',
  'السنة الدراسية الجديدة': 'New academic year',
  'الفصل الهدف': 'Target class',
  'جاري تحميل قائمة الطلبة...': 'Loading the student list...',
  'طلبة': 'students',
  'سينتقل الطلبة من': 'Students will move from',
  'للسنة الدراسية': 'for the academic year',
  'لا يوجد طلبة نشطون في هذا الفصل.': 'There are no active students in this class.',
  'الإجراء': 'Action',
  'الفصل الجديد': 'New class',
  'تخرج وأرشفة': 'Graduate and archive',
  'جاري التنفيذ...': 'Working...',
  'تخريج': 'Graduate',
  'نقل': 'Move',

  // ---- teacher subject picker ----
  'مادة مختارة': 'selected',
  'جاري تحميل المواد...': 'Loading subjects...',
  'لا توجد مواد مطابقة.': 'No matching subjects.',
  'اختيار الكل': 'Select all',
  'حالياً مع': 'currently with',
  'سيتم نقلها': 'will be moved',
  'إزالة': 'Remove',

  // ---- sentences, hints and fragments that sit beside interpolations ----
  '% لتكتمل المئة.': '% to reach 100%.',
  '+ إضافة تقدير': '+ Add band',
  '+ إضافة صف': '+ Add row',
  '. حدد ما دفعه ولي الأمر اليوم، أو تخطَّ هذه الخطوة.': '. Enter what the guardian paid today, or skip this step.',
  '. فعّل': '. Activate',
  '. لا يمكن التراجع عن هذا الإجراء.': '. This cannot be undone.',
  '. يرجى مراجعة إدارة المدرسة.': '. Please contact the school office.',
  '/ المبلغ:': '/ Amount:',
  'Course GPA يُحدد من هذا السلم حسب الدرجة النهائية للمادة. عدّل أعلى وأصغر درجة والنقاط لكل تقدير.':
    'Course GPA comes from this scale, based on the subject’s final grade. Edit the range and points for each band.',
  'Credits Earned = ساعات السنة ÷ 120 · ساعات السنة = عدد الحصص أسبوعياً × عدد الأسابيع (30) × 40 دقيقة. آخر صف في الجدول يُطبَّق على أي عدد حصص أكبر منه (≥).':
    'Credits earned = yearly hours ÷ 120 · yearly hours = periods per week × 30 weeks × 40 minutes. The last row applies to any higher number of periods (≥).',
  'Grading / GPA Scale — سلم تقدير الدرجات': 'Grading / GPA scale',
  'Legend of Credits Earned — جدول النقاط المكتسبة': 'Legend of credits earned',
  'Sibling Search / البحث عن شقيق': 'Sibling search',
  '«حفظ» يبقي الدرجات قابلة للتعديل، و«إرسال نهائي» يقفلها.': '“Save” keeps the marks editable; “Submit finally” locks them.',
  '· إجمالي': '· total',
  '· اعتمده': '· approved by',
  '· حالياً ضمن «': '· currently under “',
  '· هذه الفئة معطّلة ولا تدخل في الحساب.': '· This category is disabled and does not count.',
  '» الموجود — احذفه أو عدّل نطاقه أولاً.': '” — delete it or change its range first.',
  'أساتذة أكملوا الإدخال (': 'Teachers who finished (',
  'أساتذة لم يكملوا الإدخال (': 'Teachers still to finish (',
  'أضف اسم الفئة فقط — مثل كتب، زي مدرسي، نقل — لتختارها عند إنشاء قالب رسم.':
    'Add just a category name — books, uniform, transport — to pick from when creating a fee template.',
  'أضف فئة واحدة على الأقل من تبويب «الفئات وطرق الدفع» أولاً.': 'Add at least one category from the Categories tab first.',
  'إذا لم يكن لولي الأمر حساب دخول بعد فسيتم إنشاؤه بهذه البيانات.': 'If the guardian has no sign-in yet, one is created with these details.',
  'إنشاء مستخدم جديد للنظام': 'Create a system user',
  'إنشاء موظف': 'Create staff member',
  'ابحث بالاسم أو اسم المستخدم...': 'Search by name or username...',
  'ابحث عن مادة أو فصل...': 'Search for a subject or class...',
  'اختر الرسوم المدفوعة — ويمكنك تعديل المبلغ لدفعة جزئية.': 'Tick the fees being paid — the amount can be edited for a part payment.',
  'اختر الفصل الحالي والسنة الدراسية الجديدة، وسينتقل الطلبة إلى الصف الذي يليه. طلبة الصف الثاني عشر يتم تخريجهم وأرشفتهم، ويمكنك استرجاعهم في أي وقت من صفحة أرشيف الطلبة.':
    'Choose the current class and the new academic year, and the students move up a grade. Grade 12 students graduate and are archived, and can be restored at any time from the student archive.',
  'اختر الفصول التي تُحتسب درجاتها بهذا التقسيم. الفصل الواحد يتبع مخططاً واحداً فقط، وأي فصل تختاره هنا يُنقل إليه من مخططه السابق.':
    'Choose the classes marked under this split. A class follows exactly one scheme, and any class picked here is moved off its previous one.',
  'اختر المواد التي سيدرّسها هذا الأستاذ. لن يتمكن من إدخال درجات إلا للمواد المختارة هنا.':
    'Choose the subjects this teacher teaches. They can only enter marks for the subjects selected here.',
  'اختياري ويمكن تخطيه بدون اختيار شقيق.': 'Optional — you can skip this without picking a sibling.',
  'اسم ولي الأمر الأول وصلة القرابة مطلوبان.': 'The guardian’s first name and relation are required.',
  'اكتب الكلمة التي تريد ظهورها لجميع الطلبة...': 'Write the message to show every student...',
  'الأساتذة (': 'Teachers (',
  'الإيصال لا يُعدَّل ولا يُحذف. الخطأ يُصحَّح بإلغاء يُبقي الأصل في السجل.':
    'A receipt is never edited or deleted. A mistake is corrected by a void that keeps the original on record.',
  'الاسم أو رقم الطالب أو الرقم الوطني...': 'Name, student number or national ID...',
  'الدرجات المُدخلة لا معنى لها خارج التقسيم الذي أُدخلت عليه، لذلك سيؤدي إلغاء التفعيل إلى':
    'Marks mean nothing outside the split they were entered under, so deactivating will',
  'السنة المفعّلة (': 'Active year (',
  'الصفوف المشمولة — اختر أكثر من صف إذا كان السعر واحداً. اترك الكل بلا تحديد ليشمل كل الصفوف.':
    'Grades covered — pick several if the price is the same. Leave all unticked to cover every grade.',
  'الطلب يبقى معلقاً حتى يعتمده صاحب صلاحية الاعتماد.': 'The request stays pending until someone with approval rights accepts it.',
  'المتاح الآن': 'Available now',
  'المخطط يحدد كيف تُقسَّم الـ 100 درجة على فئات (أعمال الفصل، الاختبارات، النهائي…)، وكل فئة تحتوي بنوداً يُدخل الأستاذ درجاتها. كل صف دراسي يتبع مخططاً واحداً فقط.':
    'A scheme sets how the 100 marks are split across categories (classwork, tests, the final…), and each category holds the items a teacher marks. Each class follows exactly one scheme.',
  'المواد المسندة —': 'Assigned subjects —',
  'بحث (الاسم أو اسم المستخدم)': 'Search (name or username)',
  'بيانات الدخول —': 'Sign-in details —',
  'بيانات دخول ولي الأمر لاحقاً': 'Guardian sign-in details (later)',
  'تعديل اسم المستخدم / كلمة المرور': 'Edit username / password',
  'تقسيم الدرجات المعتمد في المدرسة، يُنشأ بضغطة واحدة بفئاته وبنوده وأوزانه.':
    'The school’s own mark split, created in one click with its categories, items and weights.',
  'تُطبَّق على الفئات التالية فقط (اتركها فارغة لتشمل كل الفئات):': 'Applies to these categories only (leave empty for all):',
  'حذف جميع الدرجات المسجّلة على هذا المخطط نهائياً': 'permanently delete every mark recorded under this scheme',
  'درجاتي —': 'My marks —',
  'درجة ستُحذف نهائياً وأوافق على المتابعة.': 'marks will be permanently deleted, and I agree to continue.',
  'شرائح الإخوة — الابن الأول عادةً بلا خصم:': 'Sibling tiers — the first child usually gets no discount:',
  'طالب وأرشفتهم': 'students and archive them',
  'طالب)': 'students)',
  'طلب خصم على «': 'Discount request for “',
  'طلبات الخصم اليدوية تنتظر هنا. لا يمكن لمن طلب الخصم أن يعتمده بنفسه. الاعتماد يعيد احتساب أقساط الطالب تلقائياً.':
    'Manual discount requests wait here. Whoever asked for a discount cannot approve it. Approving recalculates the student’s balance automatically.',
  'عند النشر يظهر زر تحميل كشف الدرجات في لوحة الطالب ولوحة ولي الأمر لهذا الفصل.':
    'Once published, a download button appears on the student and guardian dashboards for this class.',
  'عند فتح فصل دراسي يستطيع الأساتذة إدخال درجاته، ويستطيع الطلبة وأولياء الأمور رؤيتها فور حفظها. الفصل المغلق لا يظهر للطلبة ولا يمكن الإدخال فيه.':
    'While a term is open teachers can enter its marks and students and guardians see them as soon as they are saved. A closed term is hidden from students and cannot be marked.',
  'في الصف النهائي — سيتم تخريجهم وأرشفتهم بدل نقلهم.': 'are in the final grade — they will graduate and be archived rather than moved up.',
  'قواعد الخصم (': 'Discount rules (',
  'قوالب الرسوم (': 'Fee templates (',
  'لا توجد بيانات طلبة حسب الفلاتر الحالية.': 'No students match the current filters.',
  'لا توجد سنة دراسية بعد. أضف سنة من الإعدادات العامة قبل عرض التقارير المالية.':
    'There is no academic year yet. Add one in General Settings before viewing financial reports.',
  'لا توجد طلبات خصم معلقة.': 'No pending discount requests.',
  'لا توجد فصول مسجلة بعد. أنشئ الفصول أولاً من قسم الفصول.': 'No classes yet. Create them from the Classes section first.',
  'لا توجد فصول مسجلة لهذه السنة الدراسية (': 'No classes recorded for this academic year (',
  'لا توجد فصول مسجلة.': 'No classes recorded.',
  'لا توجد فصول مسجلة. أضف فصلاً أولاً ثم أضف مواده.': 'No classes recorded. Add a class first, then its subjects.',
  'لا توجد مخططات درجات بعد. أنشئ مخططاً أو استخدم أحد المخططات الجاهزة أدناه.':
    'No grading schemes yet. Create one, or use a ready-made scheme below.',
  'لا يمكن إنشاء التقرير — توجد درجات ناقصة. أكمل إدخال الدرجات التالية أولاً:':
    'The report cannot be generated — marks are missing. Complete these first:',
  'لا يمكن تعديلها. راجع الإدارة لإعادة فتحها.': 'They cannot be changed. Ask the office to reopen the sheet.',
  'لا يوجد أبناء مرتبطون بهذا الحساب. يرجى مراجعة إدارة المدرسة.': 'No children are linked to this account. Please contact the school office.',
  'لا يوجد أساتذة مطابقون.': 'No matching teachers.',
  'لا يوجد أستاذ أكمل جميع مواده بعد.': 'No teacher has finished all their subjects yet.',
  'لا يوجد أولياء أمور لهذا الفصل.': 'No guardians for this class.',
  'لا يوجد طلبة في هذا الفصل.': 'No students in this class.',
  'لا يوجد مستخدمون مطابقون.': 'No matching users.',
  'لم تتم إضافة مواد لهذا الفصل بعد.': 'No subjects added to this class yet.',
  'لم تفتح إدارة المدرسة أي فصل دراسي بعد. ستظهر الدرجات هنا فور فتحه.':
    'The school has not opened a term yet. Marks will appear here as soon as it does.',
  'لم تفتح إدارة المدرسة أي فصل دراسي بعد. ستظهر درجاتك هنا فور فتحه.':
    'The school has not opened a term yet. Your marks will appear here as soon as it does.',
  'لم تُعرَّف قوالب رسوم لصفه في هذه السنة — يمكنك إعدادها من المالية ← إعداد الرسوم.':
    'No fee templates are defined for their grade this year — set them up in Finance → Fee Setup.',
  'لم يُنشر أي كشف لهذا الفصل بعد.': 'Nothing has been published for this class yet.',
  'مثال: «الاختبارات القصيرة» بوزن 10% ثم أضف تحتها Quiz 1 إلى Quiz 4.':
    'For example “Quizzes” at 10%, then add Quiz 1 to Quiz 4 under it.',
  'مستخدمو النظام — أدمن وموظفون (': 'System users — admins and staff (',
  'ممتاز — جميع الأساتذة أرسلوا درجات كل موادهم لهذه الفترة.': 'All teachers have submitted marks for every subject this period.',
  'من': 'From',
  'من الإعدادات العامة للعودة إلى السنة الحالية.': 'in General Settings to return to the current year.',
  'من الإعدادات العامة.': 'in General Settings.',
  'مواد بدون أستاذ (': 'Subjects with no teacher (',
  'هذا النص يظهر في أعلى كشف درجات السيمستر لجميع الطلبة. اتركه فارغاً لإخفائه من التقرير.':
    'This text appears at the top of every student’s semester report. Leave it empty to hide it.',
  'هذه البيانات اختيارية ولا تمنع حفظ الطالب إذا تُركت فارغة.': 'These fields are optional and do not block saving the student.',
  'هذه القائمة تظهر لموظف المالية عند تحصيل الدفعة.': 'This list is what the cashier sees when taking a payment.',
  'هذه المواد غير مسندة لأي أستاذ، لذلك لن يدخل أحد درجاتها.': 'These subjects have no teacher, so nobody will mark them.',
  'ولا يُعمل به بعد. حدد فصوله ثم اضغط «تفعيل المخطط».': 'and not in use yet. Choose its classes, then press “Activate scheme”.',
  'وهي سنة سابقة. فعّل': 'which is a past year. Activate',
  'يتقاطع مع مخطط «': 'Overlaps the scheme “',
  'يرجى تعبئة جميع الحقول المطلوبة قبل الحفظ.': 'Please fill in every required field before saving.',
  'يستطيع هذا الأستاذ إدخال درجات المواد المختارة فقط.': 'This teacher can only enter marks for the selected subjects.',
  'يعمل النظام على سنة دراسية واحدة مفعّلة في كل وقت. عند تفعيل سنة سابقة تظهر قوائم الطلبة وصفوفهم ودرجاتهم كما كانت في تلك السنة — الطالب الذي صار في G2 يظهر في G1 — وبالرجوع إلى السنة الحالية تعود البيانات الحالية كما هي. لا يُعدَّل أي شيء بالتبديل.':
    'The system works in one active academic year at a time. Activating a past year shows students, their grades and their marks as they were then — a student now in G2 reads as G1 — and switching back restores the present exactly. Nothing is modified by switching.',
  'يمكنك بصفتك إدارياً التعديل أو إعادة فتح الكشف للأستاذ.': 'As an administrator you can edit it or reopen the sheet for the teacher.',
  'يُنشأ المستخدم الجديد كموظف نظام، وتحدد صلاحياته من القائمة التالية.':
    'The new user is created as staff; choose their permissions from the list below.',
  '— الطلبة وصفوفهم ودرجاتهم كما كانت في تلك السنة. للعودة إلى السنة الحالية فعّل':
    '— students, their grades and their marks as they were that year. To return to the current year, activate',
  '— المخطط مكتمل.': '— the scheme is complete.',
  '— تجاوزت المئة بـ': '— over 100% by',
  '— تقسيم الدرجات': '— mark split',
  '— سيتم نقلها': '— will be moved',
  '— متبقٍ': '— remaining',
  '— يُحوَّل إلى نسبة ثم يُضرب في وزن الفئة (': '— converted to a percentage and multiplied by the category weight (',
  '← العودة للفصول': '← Back to classes',
  '← العودة للمخططات': '← Back to schemes',
  '⚠ إلغاء تفعيل مخطط «': '⚠ Deactivate the scheme “',
  '⚠ متأخرات مستحقة:': '⚠ Overdue:',
  '⚠ يوجد مبلغ متأخر قدره': '⚠ There is an overdue amount of',
  '⬆ نقل': '⬆ Move',
  '＋ إضافة الفئة': '＋ Add category',
  '＋ إضافة بند': '＋ Add item',
  '🎓 تخرج وأرشفة': '🎓 Graduate and archive',
  '🎓 تخريج': '🎓 Graduate',
  '🎓 طلبة': '🎓 students',
  '🔒 تم إرسال الدرجات': '🔒 Marks submitted',
  '🕘 السنة المفعّلة الآن': '🕘 The active year is now',
  '🕘 النظام مضبوط على سنة سابقة، والأرقام والقوائم أدناه تخص': '🕘 The system is set to a past year; the figures and lists below are for',
  '🕘 تعرض الآن بيانات السنة الدراسية': '🕘 Showing data for the academic year',
  'تصميم كشف الدرجات': 'Report card designer',
  'غيّر الشعار والاسم والعناوين والمسميات والألوان — وستراها في المعاينة فوراً قبل الطباعة.': 'Change the logo, name, titles, labels and colours — and see them in the preview before printing.',
  'حفظ التصميم': 'Save design',
  'استعادة الافتراضي': 'Restore default',
  'الشعار واسم المدرسة': 'Logo and school name',
  'اسم المدرسة': 'School name',
  'إظهار الشعار': 'Show the logo',
  'عرض الشعار (بكسل)': 'Logo width (px)',
  'حذف الشعار': 'Remove logo',
  'العناوين': 'Titles',
  'عنوان كشف الكوارتر': 'Quarter report title',
  'عنوان كشف السيمستر': 'Semester report title',
  'اكتب {semester} في عنوان السيمستر ليُستبدل برقمه.': 'Write {semester} in the semester title and it is replaced by the number.',
  'مسميات بيانات الطالب': 'Student detail labels',
  'المدرسة': 'School',
  'المدير': 'Principal',
  'المعلم': 'Teacher',
  'رقم الجلوس': 'Roll number',
  'رقم التسجيل': 'Registration number',
  'ولي الأمر': 'Parent/Guardian',
  'مجموع أيام الغياب': 'Total days absent',
  'إظهار رقم الجلوس': 'Show roll number',
  'إظهار رقم التسجيل': 'Show registration number',
  'إظهار ولي الأمر': 'Show parent/guardian',
  'إظهار تاريخ التقرير': 'Show the report date',
  'أعمدة جدول الدرجات': 'Marks table columns',
  'عمود المادة': 'Subject column',
  'عمود الدرجة': 'Marks column',
  'عمود التقدير': 'Letter column',
  'إظهار عمود التقدير': 'Show the letter column',
  'عمود الدرجة النهائية': 'Final grade column',
  'الكورتر الأول': 'Quarter 1',
  'الكورتر الثاني': 'Quarter 2',
  'الكورتر الثالث': 'Quarter 3',
  'الكورتر الرابع': 'Quarter 4',
  'السيمستر الأول': 'Semester 1',
  'السيمستر الثاني': 'Semester 2',
  'اضغط Enter داخل العمود لتقسيم العنوان على سطرين.': 'Press Enter inside the field to split the heading over two lines.',
  'الملخص ومفتاح الدرجات والملاحظات': 'Summary, grading key and remarks',
  'إظهار GPA': 'Show GPA',
  'مسمى GPA': 'GPA label',
  'إظهار المجموع والحالة': 'Show totals and status',
  'مسمى المجموع': 'Total label',
  'مسمى الحالة': 'Status label',
  'نص النجاح': 'Pass text',
  'نص الرسوب': 'Fail text',
  'إظهار مفتاح الدرجات': 'Show grading key',
  'عنوان مفتاح الدرجات': 'Grading key title',
  'نص مفتاح الدرجات': 'Grading key text',
  'إظهار ملاحظات المعلم': 'Show teacher remarks',
  'عنوان ملاحظات المعلم': 'Teacher remarks heading',
  'نص ملاحظات المعلم': 'Teacher remarks text',
  'التوقيع والتذييل': 'Signature and footer',
  'إظهار التوقيع': 'Show the signature',
  'سطر التوقيع': 'Signature line',
  'صفة الموقّع': 'Signatory role',
  'مسمى توقيع السيمستر': 'Semester signature caption',
  'ملاحظة أسفل الكشف': 'Note at the foot of the sheet',
  'الألوان والخط': 'Colours and type',
  'اللون الأساسي': 'Accent colour',
  'خلفية رأس الجدول': 'Table header background',
  'خلفية المسميات': 'Label background',
  'لون الإطار': 'Border colour',
  'لون النص': 'Text colour',
  'حجم الخط': 'Font size',
  'كشف الكوارتر': 'Quarter sheet',
  'كشف السيمستر': 'Semester sheet',
  'هذه معاينة تقريبية ببيانات تجريبية — الطباعة الفعلية تأخذ بيانات الطالب.': 'An approximate preview with sample data — the printed sheet uses the real student.',
  'عرض مواد': 'Subjects of',
  'الأستاذ (اختياري)': 'Teacher (optional)',
  'بلا معلم — يمكن إسناده لاحقاً': 'No teacher — can be assigned later',
  'بلا معلم': 'No teacher',
  'تعديل بيانات الفصل': 'Edit class',
  'لا توجد فصول بعد. يرجى إضافة فصل أولاً من قسم "الفصول" قبل إضافة مادة.':
    'No classes yet. Add a class from the Classes section before adding a subject.',

  // ---- Google Classroom ----
  'ربط Google Classroom': 'Google Classroom link',
  'كل مادة هنا تقابل فصلاً واحداً في Google Classroom، ويُضاف إليه أستاذها وطلبتها من هذه الصفحة.':
    'Each subject here matches one Google Classroom course, and its teacher and students are added from this page.',
  'كيف أربط البريد؟': 'How do I link the email?',
  'إخفاء دليل الربط': 'Hide the setup guide',
  'متصل بـ Google': 'Connected to Google',
  'وضع التجربة — بلا اتصال فعلي': 'Stand-in mode — nothing is sent',
  'نطاق المدرسة': 'School domain',
  'حساب الإدارة': 'Acting account',
  'غير مضبوط': 'Not set',
  'ملف المفتاح موجود': 'Key file found',
  'ملف المفتاح غير موجود': 'Key file missing',
  'الصفحة تعمل الآن على نسخة تجريبية داخلية: كل شيء يُحفظ ويُعرض، ولا يُرسل شيء إلى Google حتى تُفعّل الربط من ملف .env.':
    'The page is running on an internal stand-in: everything is stored and shown, and nothing reaches Google until the link is switched on in .env.',
  '— اختر —': '— choose —',
  'عناوين Google للطلبة والأساتذة': 'Google addresses for students and teachers',
  'لا يُعرف أحد في Google إلا ببريده على نطاق المدرسة. لا يمكن تسجيل طالب بلا عنوان.':
    'Google knows nobody except by their address on the school domain. A student without one cannot be enrolled.',
  'حفظ العناوين': 'Save addresses',
  'اقتراح العناوين حسب': 'Suggest addresses from',
  'رقم القبول': 'Admission number',
  'اقترح للفارغين': 'Suggest for the blanks',
  'جاهزون': 'Ready',
  'بريد Google': 'Google address',
  'جاهز': 'Ready',
  'بلا بريد': 'No address',
  'لا يوجد طلبة في هذا الفصل.': 'No students in this class.',
  'المواد وفصولها في Google Classroom': 'Subjects and their Google Classroom courses',
  'رمز الانضمام': 'Join code',
  'مضاف': 'Added',
  'فتح': 'Open',
  'ناقص': 'missing',
  'إنشاء الفصل': 'Create course',
  'إعادة التسمية': 'Rename',
  'إضافة الأستاذ': 'Add teacher',
  'إضافة الطلبة': 'Add students',
  'لا توجد مواد في هذا الفصل.': 'No subjects in this class.',
  'إعادة تسمية الفصل في Google Classroom': 'Rename the Google Classroom course',
  'اختر الطلبة': 'Choose the students',
  'من ليس لديه بريد Google لا يمكن تسجيله، ويظهر معطّلاً.':
    'Anyone without a Google address cannot be enrolled, and shows as disabled.',
  'تسجيل المحدّدين': 'Enrol the selected',
  'فعّل سنة أخرى أولاً لتتمكن من حذف هذه.': 'Activate another year first to be able to delete this one.',
  'حذف السنة وكل بياناتها': 'Delete the year and its data',

  'حذف المحدّدة': 'Delete selected',
  'جاري الحذف...': 'Deleting...',
  'حذف المواد': 'Delete the subjects',

  'لها امتحان': 'Examined',
  'بلا امتحان': 'No exam',
  'مادة بلا امتحان لا تُدرج في صحيفة الدرجات ولا تدخل في المعدل.':
    'A subject with no exam is left off the report card and out of the GPA.',

  'الفصول الدراسية': 'Classes',
  'يمكن اختيار أكثر من فصل — تُضاف نفس المواد لكل فصل مختار.':
    'More than one class can be chosen — the same subjects are added to each.',
  'سيتم إنشاء': 'This creates',
  'فصل': 'classes',

  'اختر فصلاً أو أكثر': 'Choose one class or more',
  'اختر من القائمة': 'Choose from the list',
  'بحث': 'Search',

  '10 أحرف على الأقل، مع أرقام ورموز.': 'At least 10 characters, with numbers and symbols.',

  'طباعة بيانات الدخول': 'Print sign-in slip',
  'طباعة بيانات دخول الفصل': 'Print the class sign-in slips',

  // ---- cash advances ----
  'العهد': 'Cash advances',
  'صرف مبلغ لموظف لينفقه لصالح المدرسة، ثم إقفاله بما يقابله من فواتير وما تبقّى من نقد.':
    'Money handed to a member of staff to spend for the school, then closed against the receipts and whatever cash comes back.',
  'عهد مفتوحة': 'Open advances',
  'قيمتها': 'Their value',
  'غير مسوّى': 'Unaccounted',
  'مفتوحة': 'Open',
  'مقفلة': 'Settled',
  'ملغاة': 'Cancelled',
  'اسم المستلم أو الغرض': 'Holder or purpose',
  'صرف عهدة جديدة': 'Issue a new advance',
  'المستلم من الموظفين': 'Staff member',
  'بدون حساب': 'No account',
  'اسم المستلم': 'Holder',
  'الغرض': 'Purpose',
  'طريقة الصرف': 'Method',
  'المرجع': 'Reference',
  'رقم شيك مثلاً': 'a cheque number, say',
  'تاريخ الصرف': 'Issued on',
  'صرف العهدة': 'Issue the advance',
  'لا توجد عهد مطابقة.': 'No advances match.',
  'الرقم': 'No.',
  'المستلم': 'Holder',
  'المصروف': 'Spent',
  'تفاصيل': 'Details',
  'عهدة رقم': 'Advance',
  'صرفها': 'issued by',
  'مستحق للمستلم': 'Owed to the holder',
  'المرتجع': 'Returned',
  'صُرف للمستلم': 'Paid to the holder',
  'أُقفلت في': 'Settled on',
  'بنود الصرف': 'What it was spent on',
  'البيان': 'Description',
  'لم يُسجَّل أي صرف بعد.': 'Nothing has been spent against it yet.',
  'رقم الفاتورة': 'invoice number',
  'إضافة بند': 'Add a line',
  'إقفال العهدة': 'Close the advance',
  'إعادة فتح': 'Reopen',
  'إلغاء العهدة': 'Cancel the advance',

  // ---- attendance register ----
  'الحضور والغياب': 'Attendance',
  'سجّل حضور كل فصل يوماً بيوم، واطبع كشف الشهر ليستعمله المشرفون ثم أدخل ما سجّلوه.':
    'Mark each class day by day, print the month for the supervisors, then enter what they recorded.',
  'تسجيل اليوم': "Today's register",
  'كشف الشهر': 'Monthly sheet',
  'اختر الفصل': 'Choose the class',
  'الشهر': 'Month',
  'السنة': 'Year',
  'الجميع حاضر': 'All present',
  'الجميع غائب': 'All absent',
  'مسح التحديد': 'Clear marks',
  'حاضر': 'Present',
  'غائب': 'Absent',
  'بلا تحديد': 'Unmarked',
  'اختياري': 'Optional',
  'حفظ حضور اليوم': "Save today's register",
  'لا يوجد طلبة مسجلون في هذا الفصل.': 'No students are enrolled in this class.',
  'طباعة كشف فارغ للمشرفين': 'Print a blank sheet for the supervisors',
  'طباعة الكشف معبّأً': 'Print the sheet filled in',
  'جاري التجهيز...': 'Preparing...',
  'الكشف الفارغ يحمل أسماء الطلبة وأيام الشهر ليُملأ بخط اليد. الكشف المعبّأ يعرض ما أُدخل في المنظومة مع مجاميع كل طالب.':
    'The blank sheet carries the students’ names and the days of the month to be filled in by hand. The filled sheet shows what was entered here, with each student’s totals.',
  'غياب': 'Absences',
  'الأيام المسجّلة': 'Days recorded',

  // ---- school calendar ----
  'تقويم المدرسة': 'School calendar',
  'أضف النشاطات والعطلات والامتحانات بألوانها — يراها أولياء الأمور والطلبة والأساتذة.':
    'Add activities, holidays and exams in their own colours — parents, students and teachers all see them.',
  'نشاطات المدرسة وعطلاتها ومواعيدها المهمة.': 'The school’s activities, holidays and important dates.',
  'هذا الشهر': 'This month',
  'إضافة فعالية': 'Add event',
  'تعديل فعالية': 'Edit event',
  'فعاليات الشهر': 'This month’s events',
  'لا توجد فعاليات هذا الشهر.': 'No events this month.',
  'النوع': 'Kind',
  'اللون': 'Colour',
  'من تاريخ': 'From',
  'إلى تاريخ': 'To',
  'يوم كامل': 'All day',
  'من الساعة': 'From',
  'إلى الساعة': 'To',
  'المكان': 'Location',
  'التفاصيل': 'Details',

  'مواد غير مرتبطة بفصل': 'Subjects with no class',
  'هذه المواد لا تنتمي إلى أي فصل، فلا يراها طلابها ولا تظهر في القوائم أعلاه. اختر الفصل ثم حدّد المواد التي تتبعه.':
    'These subjects belong to no class, so their students cannot see them and they do not appear in the lists above. Choose the class, then tick the subjects that belong to it.',
  'ربط بالفصل': 'Link to class',

  // ---- the in-house classroom ----
  'الفصل الإلكتروني': 'Classroom',
  'لا توجد مواد متاحة لك بعد.': 'No subjects are open to you yet.',
  'موادي': 'My subjects',
  'نوع المنشور': 'Post type',
  'إعلان': 'Announcement',
  'مادة تعليمية': 'Material',
  'العنوان': 'Title',
  'السماح بالتعليقات': 'Allow comments',
  'النص': 'Text',
  'اكتب ما تريد قوله للفصل...': 'Write what you want to tell the class...',
  'نشر': 'Post',
  'جاري النشر...': 'Posting...',
  'لا توجد منشورات بعد.': 'Nothing posted yet.',
  'مثبّت': 'Pinned',
  'مسودة': 'Draft',
  'تثبيت': 'Pin',
  'إلغاء التثبيت': 'Unpin',
  'ملف': 'File',
  'عرض كل التعليقات': 'Show all comments',
  'اكتب تعليقاً...': 'Write a comment...',
  'إرسال': 'Send',
  'عرض منشورات أقدم': 'Show older posts',

  'كيف تربط بريد المدرسة بالمنظومة — خطوة بخطوة': 'Linking the school email to the system — step by step',
  'تُنفَّذ الخطوات مرة واحدة فقط. الخطوات من 1 إلى 8 في لوحات Google وملف الإعدادات، والخطوتان الأخيرتان في هذه الصفحة.':
    'These are done once. Steps 1 to 8 happen in Google’s consoles and the settings file; the last two happen on this page.',
}

/**
 * Translate a page string. In Arabic it hands back exactly what was written; in
 * English it returns the mapped text, or the Arabic if none is mapped yet.
 */
export function tr(arabic) {
  if (isArabic.value) return arabic

  return en[arabic] ?? arabic
}

export function usePhrases() {
  return { tr }
}
